//! A persistent, on-disk cache of tag-read results, backed by `redb`,
//! keyed by a file's path, size, and modification time. Confines `redb`
//! to this one file - nothing outside it names a `redb` type, matching
//! the same encapsulation rule `metadata::tags` already follows for
//! `lofty`.
//!
//! Only the fields a real tag read is expensive to produce
//! (artist/album/genre/has_art) are cached. Title/track number stay
//! uncached - they come from `FilenameMetadata`, which is cheap, so
//! recomputing them on every call means a rename is reflected
//! immediately, with no invalidation logic needed for them at all.
//!
//! Rebuildable, not authoritative: every cached record can be
//! regenerated by re-reading the file, so writes use
//! `Durability::None` - fast, and a crash loses at most the last few
//! writes, never correctness (a lost write just means one file's tags
//! get re-parsed on the next scan, nothing worse). A cache write's own
//! failure is swallowed for the same reason: a scan must never fail
//! because its optional speedup failed to persist.
//!
//! Generic over the inner provider, unlike most of this crate's other
//! single-implementation extension points: real production code always
//! instantiates `CachedTagMetadata<TagMetadata>`, but the tests below
//! need to isolate the caching logic itself (hit/miss/prune behavior)
//! from `lofty`'s own behavior, which needs a substitutable `inner`.

use std::collections::HashSet;
use std::path::{Path, PathBuf};
use std::time::SystemTime;

use redb::{Database, Durability, ReadableDatabase, ReadableTable, TableDefinition};
use serde::{Deserialize, Serialize};

use crate::core::metadata_provider::{Metadata, MetadataProvider};
use crate::metadata::filename::FilenameMetadata;

const TABLE: TableDefinition<&str, &str> = TableDefinition::new("tags");

#[derive(Serialize, Deserialize)]
struct CachedTags {
    size: u64,
    modified_unix_nanos: u128,
    artist: Option<String>,
    album: Option<String>,
    genre: Option<String>,
    has_art: bool,
}

pub struct CachedTagMetadata<P> {
    db: Database,
    inner: P,
}

impl<P: MetadataProvider> CachedTagMetadata<P> {
    /// Opens the cache database at `path`, creating it if it doesn't
    /// exist yet. `inner` is consulted, and its result cached, on
    /// every miss.
    pub fn open(path: &Path, inner: P) -> std::io::Result<Self> {
        let db = Database::create(path).map_err(|err| std::io::Error::other(err.to_string()))?;
        Ok(CachedTagMetadata { db, inner })
    }

    fn lookup(&self, key: &str, size: u64, modified_unix_nanos: u128) -> Option<CachedTags> {
        let read_txn = self.db.begin_read().ok()?;
        let table = read_txn.open_table(TABLE).ok()?;
        let guard = table.get(key).ok()??;
        let cached: CachedTags = serde_json::from_str(guard.value()).ok()?;
        (cached.size == size && cached.modified_unix_nanos == modified_unix_nanos).then_some(cached)
    }

    fn store(&self, key: &str, cached: &CachedTags) {
        let Ok(json) = serde_json::to_string(cached) else {
            return;
        };
        let Ok(mut write_txn) = self.db.begin_write() else {
            return;
        };
        let _ = write_txn.set_durability(Durability::None);
        {
            let Ok(mut table) = write_txn.open_table(TABLE) else {
                return;
            };
            let _ = table.insert(key, json.as_str());
        }
        let _ = write_txn.commit();
    }

    /// Every key currently stored, or an empty list on any error -
    /// used only by `retain_only` and by this module's own tests.
    fn all_keys(&self) -> Vec<String> {
        (|| -> Option<Vec<String>> {
            let read_txn = self.db.begin_read().ok()?;
            let table = read_txn.open_table(TABLE).ok()?;
            let mut keys = Vec::new();
            for entry in table.iter().ok()? {
                let (key, _) = entry.ok()?;
                keys.push(key.value().to_string());
            }
            Some(keys)
        })()
        .unwrap_or_default()
    }
}

impl<P: MetadataProvider> MetadataProvider for CachedTagMetadata<P> {
    fn metadata(&self, path: &Path) -> Metadata {
        let filename = FilenameMetadata.metadata(path);
        let Ok(stat) = std::fs::metadata(path) else {
            return self.inner.metadata(path);
        };
        let Some(modified_unix_nanos) = unix_nanos(stat.modified().ok()) else {
            return self.inner.metadata(path);
        };
        let key = path.to_string_lossy();

        if let Some(cached) = self.lookup(&key, stat.len(), modified_unix_nanos) {
            return Metadata {
                artist: cached.artist,
                album: cached.album,
                genre: cached.genre,
                has_art: cached.has_art,
                ..filename
            };
        }

        let fresh = self.inner.metadata(path);
        self.store(
            &key,
            &CachedTags {
                size: stat.len(),
                modified_unix_nanos,
                artist: fresh.artist.clone(),
                album: fresh.album.clone(),
                genre: fresh.genre.clone(),
                has_art: fresh.has_art,
            },
        );
        fresh
    }

    /// Two passes, not one: a slight race between them is harmless for
    /// a rebuildable cache (a key added between the passes gets
    /// wrongly deleted at worst, and simply gets re-added on its next
    /// miss), so a read pass to find stale keys followed by a separate
    /// write pass to remove them is simpler than trying to do both in
    /// one transaction.
    fn retain_only(&self, live_paths: &[PathBuf]) {
        let live: HashSet<String> = live_paths
            .iter()
            .map(|p| p.to_string_lossy().into_owned())
            .collect();
        let stale: Vec<String> = self
            .all_keys()
            .into_iter()
            .filter(|key| !live.contains(key))
            .collect();
        if stale.is_empty() {
            return;
        }

        let Ok(mut write_txn) = self.db.begin_write() else {
            return;
        };
        let _ = write_txn.set_durability(Durability::None);
        {
            let Ok(mut table) = write_txn.open_table(TABLE) else {
                return;
            };
            for key in &stale {
                let _ = table.remove(key.as_str());
            }
        }
        let _ = write_txn.commit();
    }
}

fn unix_nanos(modified: Option<SystemTime>) -> Option<u128> {
    modified?
        .duration_since(SystemTime::UNIX_EPOCH)
        .ok()
        .map(|d| d.as_nanos())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicUsize, Ordering};
    use std::time::Duration;

    /// A fake `MetadataProvider` that counts real calls, so the cache's
    /// hit/miss behavior can be tested without any real file I/O or
    /// `lofty` parsing.
    struct CountingProvider {
        calls: AtomicUsize,
        artist: String,
    }

    impl CountingProvider {
        fn new(artist: &str) -> Self {
            CountingProvider {
                calls: AtomicUsize::new(0),
                artist: artist.to_string(),
            }
        }

        fn call_count(&self) -> usize {
            self.calls.load(Ordering::SeqCst)
        }
    }

    impl MetadataProvider for CountingProvider {
        fn metadata(&self, path: &Path) -> Metadata {
            self.calls.fetch_add(1, Ordering::SeqCst);
            FilenameMetadata.metadata(path).with_artist(&self.artist)
        }
    }

    trait WithArtist {
        fn with_artist(self, artist: &str) -> Metadata;
    }

    impl WithArtist for Metadata {
        fn with_artist(self, artist: &str) -> Metadata {
            Metadata {
                artist: Some(artist.to_string()),
                ..self
            }
        }
    }

    fn cache_at(dir: &Path, inner: CountingProvider) -> CachedTagMetadata<CountingProvider> {
        CachedTagMetadata::open(&dir.join("cache.redb"), inner).unwrap()
    }

    #[test]
    fn a_second_identical_call_is_a_cache_hit() {
        let dir = tempfile::tempdir().unwrap();
        let track = dir.path().join("track.mp3");
        std::fs::write(&track, b"content").unwrap();

        let cache = cache_at(dir.path(), CountingProvider::new("Artist"));

        let first = cache.metadata(&track);
        assert_eq!(first.artist.as_deref(), Some("Artist"));
        assert_eq!(cache.inner.call_count(), 1);

        let second = cache.metadata(&track);
        assert_eq!(second, first);
        assert_eq!(
            cache.inner.call_count(),
            1,
            "an unchanged file must not call the inner provider again"
        );
    }

    #[test]
    fn touching_the_file_forward_is_a_miss_again() {
        let dir = tempfile::tempdir().unwrap();
        let track = dir.path().join("track.mp3");
        std::fs::write(&track, b"content").unwrap();

        let cache = cache_at(dir.path(), CountingProvider::new("Artist"));
        cache.metadata(&track);
        assert_eq!(cache.inner.call_count(), 1);

        // A real filesystem mtime can have coarser resolution than a
        // fast test loop - move it forward by a whole second to
        // guarantee a different `modified` value, not just a later
        // wall-clock instant.
        let future = SystemTime::now() + Duration::from_secs(2);
        let file = std::fs::File::open(&track).unwrap();
        file.set_modified(future).unwrap();

        cache.metadata(&track);
        assert_eq!(
            cache.inner.call_count(),
            2,
            "a changed mtime must force a fresh read"
        );
    }

    #[test]
    fn a_garbage_cached_value_is_treated_as_a_miss_not_a_panic() {
        let dir = tempfile::tempdir().unwrap();
        let track = dir.path().join("track.mp3");
        std::fs::write(&track, b"content").unwrap();

        let cache = cache_at(dir.path(), CountingProvider::new("Artist"));
        let key = track.to_string_lossy().into_owned();

        let write_txn = cache.db.begin_write().unwrap();
        {
            let mut table = write_txn.open_table(TABLE).unwrap();
            table.insert(key.as_str(), "not valid json").unwrap();
        }
        write_txn.commit().unwrap();

        let metadata = cache.metadata(&track);
        assert_eq!(metadata.artist.as_deref(), Some("Artist"));
        assert_eq!(cache.inner.call_count(), 1);
    }

    #[test]
    fn a_cache_persists_across_separate_instances_at_the_same_path() {
        let dir = tempfile::tempdir().unwrap();
        let track = dir.path().join("track.mp3");
        std::fs::write(&track, b"content").unwrap();
        let cache_path = dir.path().join("cache.redb");

        {
            let cache =
                CachedTagMetadata::open(&cache_path, CountingProvider::new("Artist")).unwrap();
            cache.metadata(&track);
        }

        let reopened =
            CachedTagMetadata::open(&cache_path, CountingProvider::new("Different")).unwrap();
        let metadata = reopened.metadata(&track);
        assert_eq!(
            metadata.artist.as_deref(),
            Some("Artist"),
            "the cached value from the first instance must survive reopening the same file"
        );
        assert_eq!(reopened.inner.call_count(), 0);
    }

    #[test]
    fn retain_only_removes_entries_for_paths_no_longer_present() {
        let dir = tempfile::tempdir().unwrap();
        let keep = dir.path().join("keep.mp3");
        let drop_me = dir.path().join("drop.mp3");
        std::fs::write(&keep, b"content").unwrap();
        std::fs::write(&drop_me, b"content").unwrap();

        let cache = cache_at(dir.path(), CountingProvider::new("Artist"));
        cache.metadata(&keep);
        cache.metadata(&drop_me);
        assert_eq!(cache.all_keys().len(), 2);

        cache.retain_only(std::slice::from_ref(&keep));

        let remaining = cache.all_keys();
        assert_eq!(remaining, vec![keep.to_string_lossy().into_owned()]);

        // Confirm the dropped entry is really gone, not just excluded
        // from listing: browsing it again is a real miss.
        cache.metadata(&drop_me);
        assert_eq!(cache.inner.call_count(), 3);
    }

    #[test]
    fn retain_only_with_no_stale_entries_does_nothing() {
        let dir = tempfile::tempdir().unwrap();
        let track = dir.path().join("track.mp3");
        std::fs::write(&track, b"content").unwrap();

        let cache = cache_at(dir.path(), CountingProvider::new("Artist"));
        cache.metadata(&track);
        cache.retain_only(std::slice::from_ref(&track));
        assert_eq!(cache.all_keys().len(), 1);
    }
}
